<?php

return apply_filters( 'cater_waiter_filter_labels', [
    'welcome_title'             => __( 'Select Pickup or Delivery for Your Catering Order', 'cater_waiter' ),
    'delivery_minimum'          => __( 'Delivery minimum is $%VALUE%.', 'cater_waiter' ),
    'hours_in_advance'          => __( 'All orders must be placed a minimum of %VALUE% hours in advance.', 'cater_waiter' ),
    'hours_in_advance_error'    => __( 'Date must be a minimum of %VALUE% hours in advance.', 'cater_waiter' ),
    'button_pickup'             => __( 'Pickup', 'cater_waiter' ),
    'button_delivery'           => __( 'Delivery', 'cater_waiter' ),
    'select_pickup_location'    => __( 'Select Pickup Location', 'cater_waiter' ),
    'label_zip_code_action'     => __( 'Enter your zip code and we\'ll show you nearby %VALUE%\'s locations', 'cater_waiter' ),
    'label_zip_code_prompt'     => __( 'Enter Zip Code', 'cater_waiter' ),
    'select_this_location'      => __( 'Select This Location', 'cater_waiter' ),
    'delivery_address_title'    => __( 'Enter Your Delivery Address', 'cater_waiter' ),
    'order_details_title'       => __( 'Order Details', 'cater_waiter' ),
    'order_type_title'          => __( 'Order Type', 'cater_waiter' ),
    'change_order_to_delivery'  => __( 'Change to Delivery', 'cater_waiter' ),
    'change_order_to_pickup'    => __( 'Change to Pickup', 'cater_waiter' ),
    'pickup_location_title'     => __( 'Pickup Location', 'cater_waiter' ),
    'pickup_time_title'         => __( 'Pickup Time', 'cater_waiter' ),
    'schedule_order_title'      => __( 'Schedule Your %VALUE%', 'cater_waiter' ),
    'label_date_prompt'         => __( 'Date', 'cater_waiter' ),
    'label_time_prompt'         => __( 'Time', 'cater_waiter' ),
    'button_continue'           => __( 'Continue', 'cater_waiter'),
	'delivery_location'         => __( 'Delivery Location', 'cater_waiter'),
	'change_delivery_location'  => __( 'Change Delivery Location', 'cater_waiter'),
	'catering_menu_title'       => __( 'Select Your Food', 'cater_waiter' ),
	'add_to_cart_title'         => __( 'Add To Cart', 'cater_waiter' ),
	'add_to_cart_button'        => __( 'Add To Cart', 'cater_waiter' ),
	'add_more_button'           => __( 'Add More', 'cater_waiter' ),
] );